### ISSUE TITLE
this module is not es5

### ISSUE THREAD

**Issue by jianming1999** [nuxt-contrib/defu#9]
this module is not es5

**Comment by erwanjugand** [comment]
I raise, impossible to use it in projects wanting to support IE

**Comment by pi0** [comment]
ES5 compatibility has been improved in v0.0.4.

**Comment by suits-at** [comment]
The new release from yesterday (v3.2.0 and v.3.2.1) broke IE11 support again. Could you please improve ES5 compatibility in your newest relase aswell @pi0? The version before that (v3.1.0) works fine.

**Comment by pi0** [comment]
Thanks for notice @suits-at. Temporary fixed by reverting to bili till supporting with new build tool (siroc)
